sudo: required
arch:
  - amd64
  - ppc64le
language: C
services:
  - docker
before_install:
  - docker build -t toddy15/isoquery .
script:
  - docker run -v $PWD:/isoquery -w /isoquery toddy15/isoquery /bin/sh -c "./configure && make && make check"
